### ISSUE TITLE
我用它扫描了一个wordpress ，确实提示了xmlrpc.php，但完全不提示wordpress啊

### ISSUE THREAD

**Issue by SanStardust** [winezer0/whatweb-plus#1]
![image](https://user-images.githubusercontent.com/37255994/130204926-b560a0a7-9e9a-446a-b409-162d6885f75d.png)

**Comment by SanStardust** [comment]
所以它也不会提示其他的cms名字对嘛，那这个工具跟dirmap之类目录扫描工具的有啥区别呢，跟云悉的区别呢。

**Comment by winezer0** [comment]
很明显，你调用的是whatweb.exe，并且没有指定插件文件夹

whatweb.exe为了缩小打包体积，仅包含简单的基础插件，请-p指定插件目录调用。
