### ISSUE TITLE
扫描错误undefined method `strip' for nil:NilClass

### ISSUE THREAD

**Issue by zhin2929** [winezer0/whatweb-plus#2]
```
ERROR Opening: http://192.168.1.160/Pass-02/index.php - undefined method `strip' for nil:NilClass
ERROR Opening: http://192.168.1.160/favicon.ico - undefined method `strip' for nil:NilClass
ERROR Opening: http://192.168.1.160/ - undefined method `strip' for nil:NilClass
ERROR Opening: http://192.168.1.160/robots.txt - undefined method `strip' for nil:NilClass
ERROR Opening: http://192.168.1.160/license.txt - undefined method `strip' for nil:NilClass
ERROR Opening: http://192.168.1.160/readme.txt - undefined method `strip' for nil:NilClass
ERROR Opening: http://192.168.1.160/logo.gif - undefined method `strip' for nil:NilClass
ERROR Opening: http://192.168.1.160/index.html - undefined method `strip' for nil:NilClass
```
用原版扫描就没问题，这是一个本地靶场。
请问是什么原因呢？

**Comment by winezer0** [comment]
你好，才看到消息，提交BUG我们一般都在WX群里面。

这个靶场环境能给一下吗？或者我远程测试一下。

这个应该是在获取服务器响应内容时失败了。

然后测试时需要排除一下插件原因。

相关涉及到strip的函数有

`\whatweb.rb(603):         $CUSTOM_HEADERS['Cookie'] = File.readlines(arg).delete_if { |line| line.strip =~ /^$/ }.map { |line| line.strip.sub(/([^;])$/, '\1;') }.join(' ')

\lib\extend-http.rb(239):         value << line.strip

\lib\extend-http.rb(242):         key, value = line.strip.split(/\s*:\s*/, 2)

\lib\target.rb(417):               metarefresh = decode_html_entities(metarefresh).strip

\lib\whatweb\scan.rb(144):         urls.flatten.reject { |u| u.nil? }.map { |u| u.strip }.reject { |u| u.eql?('') }.each do |url|

\lib\whatweb\scan.rb(154):         File.open(inputfile).readlines.each(&:strip!).reject { |line| line.start_with?('#') || line.eql?('') }.each do |line|

\my-plugins\plugins-base\title.rb(16): m << {:name=>"page title",:string=>title.strip}

\my-plugins\plugins-cms\meta-refresh.rb(15): meta_refresh = decode_html_entities(meta_refresh).strip

\my-plugins\plugins-cms\wordpress\wordpress.rb(90): links = @body.scan(%r{(href|src)="([^"]*/wp-content/[^"]*)}).map { |x| x[1].strip }.flatten

\my-plugins\plugins-cms\wordpress\wordpress.rb(99): links= @body.scan(/(href|src)="([^"]*\/wp-includes\/[^"]*)/).map {|x| x[1].strip }.flatten

\my-plugins\plugins-cms\wordpress\wordpress.rb(109): links= @body.scan(/(href|src)="([^"]*\/wp-json\/[^"]*)/).map {|x| x[1].strip }.flatten

\plugin-development\migrate-plugins-to-v0.5.rb(88): puts `#{cmd}`.strip.yellow

\plugin-development\migrate-plugins-to-v0.5.rb(132): 				author.strip!

\plugin-development\migrate-plugins-to-v0.5.rb(133): 				author = nil if author.strip.empty?

\plugin-development\migrate-plugins-to-v0.5.rb(271): 	response = STDIN.gets.strip

\plugin-development\migrate-plugins-to-v0.5.rb(294): 	response = STDIN.gets.strip
`
