### ISSUE TITLE
命令执行反馈无plugins

### ISSUE THREAD

**Issue by nanioo** [winezer0/whatweb-plus#3]
![WX20220520-165838](https://user-images.githubusercontent.com/7869766/169499183-dcbfda87-61ca-4503-a59d-42badacf0ca6.png)
另有报错
![WX20220520-173029](https://user-images.githubusercontent.com/7869766/169499273-c43674c4-fab5-46b8-a247-f284ff610624.png)

**Comment by winezer0** [comment]
关于报错应该是网络问题，这个报错是说明没有响应内容。
没有插件显示，您是能发布一下运行的命令吗？
如果是使用已打包好的exe版本，是没有内置所有插件的，需要指定插件目录。

**Comment by winezer0** [comment]
ruby whatweb.rb -l
![image](https://user-images.githubusercontent.com/46115146/169695412-dc6a4e9a-f9b4-4a16-a643-467c00e9f388.png)

whatweb.exe www.baidu.com
![image](https://user-images.githubusercontent.com/46115146/169695462-7183fea5-0334-4411-bb3a-ff90331469ae.png)

**Comment by nanioo** [comment]
> 版本

是在mac用打包好的指令，请问路径如何指定？

**Comment by nanioo** [comment]
不是exe的版本

**Comment by nanioo** [comment]
ruby ./whatweb.rb -l
WhatWeb Plugin List

Plugin                        Website
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

Total: 0 Plugins

Hint:
For complete plugin descriptions use : whatweb --info-plugins <SEARCH>
Use it without a search term for a complete description of all plugins.

**Comment by nanioo** [comment]
MacBook-Pro:whatweb-plus$ ./whatweb --plugins +my-plugins www.baidu.com
+my-plugins
+my-plugins
ERROR Opening: https://www.baidu.com - undefined method `strip' for nil:NilClass
ERROR Opening: http://www.baidu.com/ - undefined method `strip' for nil:NilClass
ERROR Opening: http://www.baidu.com/favicon.ico - undefined method `strip' for nil:NilClass
ERROR Opening: http://www.baidu.com/license.txt - undefined method `strip' for nil:NilClass
ERROR Opening: http://www.baidu.com/readme.txt - undefined method `strip' for nil:NilClass
ERROR Opening: http://www.baidu.com/logo.gif - undefined method `strip' for nil:NilClass
ERROR Opening: http://www.baidu.com/index.html - undefined method `strip' for nil:NilClass
ERROR Opening: http://www.baidu.com - undefined method `strip' for nil:NilClass
ERROR Opening: http://www.baidu.com/robots.txt - undefined method `strip' for nil:NilClass
ERROR Opening: https://www.baidu.com/ - undefined method `strip' for nil:NilClass
ERROR Opening: https://www.baidu.com/favicon.ico - undefined method `strip' for nil:NilClass
ERROR Opening: https://www.baidu.com/index.html - undefined method `strip' for nil:NilClass
ERROR Opening: https://www.baidu.com/readme.txt - undefined method `strip' for nil:NilClass
ERROR Opening: https://www.baidu.com/license.txt - undefined method `strip' for nil:NilClass
ERROR Opening: https://www.baidu.com/robots.txt - undefined method `strip' for nil:NilClass
ERROR Opening: https://www.baidu.com/logo.gif - undefined method `strip' for nil:NilClass
MacBook-Pro:whatweb-plus$ ./whatweb -l
WhatWeb Plugin List

Plugin                        Website
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

Total: 0 Plugins

Hint:
For complete plugin descriptions use : whatweb --info-plugins <SEARCH>
Use it without a search term for a complete description of all plugins.

MacBook-Pro:whatweb-plus$ ping www.baidu.com
PING www.baidu.com (36.152.44.96): 56 data bytes
64 bytes from 36.152.44.96: icmp_seq=0 ttl=54 time=15.658 ms
64 bytes from 36.152.44.96: icmp_seq=1 ttl=54 time=19.301 ms
^C
--- www.baidu.com ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 15.658/17.479/19.301/1.822 ms

./whatweb -V
WhatWeb version 0.5.5.13 ( https://morningstarsecurity.com/research/whatweb/ )

**Comment by winezer0** [comment]
尝试将命令修改为
./whatweb.rb -p my-plugins -l 试试

您的ruby版本是多少呢？
原始的whatweb是否可以使用？
