### ISSUE TITLE
kali2022环境下执行whatweb报错/usr/bin/env: “ruby\r”: 没有那个文件或目录

### ISSUE THREAD

**Issue by like4h** [winezer0/whatweb-plus#5]
环境kali2022 ruby2.7 安装目录/opt/whatweb+ 软链接ln -s /opt/whatweb+/whatweb+ /usr/bin

![image](https://user-images.githubusercontent.com/100220065/184532652-fa7eebcf-8c32-40e5-a6d5-ef2303449664.png)

**Comment by winezer0** [comment]
这个应该是whatweb+第一行换行符的问题，需要手动编辑一下。
