### ISSUE TITLE
安装后运行找不到plugins

### ISSUE THREAD

**Issue by pzy8023** [winezer0/whatweb-plus#6]
whatweb --list-plugins

WhatWeb Plugin List

Plugin                        Website
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

Total: 0 Plugins

Hint:
For complete plugin descriptions use : whatweb --info-plugins <SEARCH>
Use it without a search term for a complete description of all plugins.

**Comment by winezer0** [comment]
使用exe运行时,需要指定插件目录
