### ISSUE TITLE
新-指纹库/建议

### ISSUE THREAD

**Issue by JiuZero** [winezer0/whatweb-plus#8]
Kscan20000+指纹：https://github.com/lcvvvv/kscan

**Comment by JiuZero** [comment]
CMS和中间件指纹库：
https://github.com/Lucifer1993/cmsprint

**Comment by winezer0** [comment]
如果参考多个指纹库的话会导致相同的指纹太多了
https://github.com/0x727/FingerprintHub
看这个怎么样？如果可以的话就自动化的转化这个指纹库的内容到whatweb

**Comment by JiuZero** [comment]
这个指纹库看起来很久没有更新了
据我看来，这款指纹库的指纹并不是那么地全面，我曾使用过与它关联的工具afrog，nuclei及ShuiZe，效果并不是很好
似乎它目前所存储的所有指纹Whatweb-plus中都已包含有了～

**Comment by JiuZero** [comment]
如果可以自动化转化的话，你可以尝试着在转化后作下自动化去重处理，这样也能够在一定程度上完善WhatWeb-plus的指纹库，但或许去重后所留有的指纹并没有多少

**Comment by winezer0** [comment]
自动化去重处理目前没有办法实现
